spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: beta@123

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  #JPA settings
  jpa.hibernate.ddl-auto: create

#Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

dummyService:
  port: 8081
  address: 127.0.0.1



